version: "3.8"

services:
  dev-db:
    container_name: "workoutDB"
    image: postgres:alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
